### ISSUE TITLE
Fetching data: "Cannot read property 'data' of undefined"

### ISSUE THREAD

**Issue by jorgeorejas** [DavideViolante/socialblade-com-api#41]
I'm not able to fetch the data from the api, It returns an error with the source even using `'twitter'`. Hope you could help me

**Comment by jorgeorejas** [comment]
Update:

`
const { socialblade } = require('socialblade-com-api');

const api_key = '<my_key>';

const baseURL = `http://api.scraperapi.com?api_key=${api_key}&url=`;

async function instagramFollowers() {
  let participantsAndFollowers = [];

  console.log('getting data for Jorge Orejas');

  let response = await socialblade(baseURL, 'instagram', 'orejasjorge');

  participantsAndFollowers.push({
    response
  });
  await delay(1000);

  console.log(participantsAndFollowers);
}

instagramFollowers()
  .then(() => {
    console.log('all done');
  })
  .catch((err) => {
    console.log(err);
  });
`

After trying to use this code to fetch the data from my instagram account I get this error 

`
getting fata for Jorge Orejas
TypeError: Cannot read property 'data' of undefined
    at getOutput (/Users/jorgeorejasrojo/Dev/Adivias-SaaS/node_modules/socialblade-com-api/functions.js:30:43)
    at socialblade (/Users/jorgeorejasrojo/Dev/Adivias-SaaS/node_modules/socialblade-com-api/index.js:27:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async instagramFollowers (/Users/jorgeorejasrojo/Dev/Adivias-SaaS/utils/twitter.js:12:18) {stack: 'TypeError: Cannot read property 'data' of und…rojo/Dev/Adivias-SaaS/utils/twitter.js:12:18)', message: 'Cannot read property 'data' of undefined'}
No debugger available, can not send 'variables'
Failed once, retrying...
TypeError: Cannot read property 'data' of undefined
    at getOutput (/Users/jorgeorejasrojo/Dev/Adivias-SaaS/node_modules/socialblade-com-api/functions.js:30:43)
    at socialblade (/Users/jorgeorejasrojo/Dev/Adivias-SaaS/node_modules/socialblade-com-api/index.js:27:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async instagramFollowers (/Users/jorgeorejasrojo/Dev/Adivias-SaaS/utils/twitter.js:12:18) {stack: 'TypeError: Cannot read property 'data' of und…rojo/Dev/Adivias-SaaS/utils/twitter.js:12:18)', message: 'Cannot read property 'data' of undefined'}
No debugger available, can not send 'variables'
Failed once, retrying...
TypeError: Cannot read property 'data' of undefined
    at getOutput (/Users/jorgeorejasrojo/Dev/Adivias-SaaS/node_modules/socialblade-com-api/functions.js:30:43)
    at socialblade (/Users/jorgeorejasrojo/Dev/Adivias-SaaS/node_modules/socialblade-com-api/index.js:27:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async instagramFollowers (/Users/jorgeorejasrojo/Dev/Adivias-SaaS/utils/twitter.js:12:18) {stack: 'TypeError: Cannot read property 'data' of und…rojo/Dev/Adivias-SaaS/utils/twitter.js:12:18)', message: 'Cannot read property 'data' of undefined'}
No debugger available, can not send 'variables'
Request failed too many times, aborting.
`

**Comment by DavideViolante** [comment]
Thank you for letting me know. Socialblade website has increased its anti scraping system and Scraperapi fails the request for the page.
The actual page returned in the following:

![socialblade](https://user-images.githubusercontent.com/6844116/130425030-bc38d50b-726d-40ec-8e09-9c78445017f4.png)



So at this time this repo is not working anymore. I will try to find a way or I will delete the repo altogether.

**Comment by DavideViolante** [comment]
I found out that this works again using Puppeteer, I released a new version.
